#Gradle
org.gradle.jvmargs=-Xmx2048M -Dkotlin.daemon.jvm.options\="-Xmx2048M"
#Kotlin
kotlin.code.style=official
#Android
android.useAndroidX=true
#MPP
#kotlin.mpp.enableGranularSourceSetsMetadata=true
#kotlin.native.enableDependencyPropagation=false
#kotlin.mpp.enableCInteropCommonization=true
#kotlin.mpp.hierarchicalStructureSupport=false
#kotlin.mpp.enableCompatibilityMetadataVariant=true
kotlin.jvm.target.validation.mode=IGNORE

############################## UPLOAD ###########################

SONATYPE_HOST=CENTRAL_PORTAL
RELEASE_SIGNING_ENABLED=false

# Maven ??
GROUP=com.baishengye.signalrkore
POM_ARTIFACT_ID=signalrkore
VERSION_NAME=0.0.1

# POM ????
POM_NAME=SignalR Kore
POM_DESCRIPTION=Connect to SignalR Core server with library written in Kotlin and coroutines.
POM_INCEPTION_YEAR=2025
POM_URL=https://github.com/baishengye/SignalRKore

# ???
POM_LICENSE_NAME=The Apache Software License, Version 2.0
POM_LICENSE_URL=https://www.apache.org/licenses/LICENSE-2.0.txt
POM_LICENSE_DIST=repo

# SCM??????
POM_SCM_CONNECTION=scm:git@github.com:baishengye/SignalRKore.git
POM_SCM_DEV_CONNECTION=scm:git@github.com:baishengye/SignalRKore.git
POM_SCM_URL=https://github.com/baishengye/SignalRKore

# ?????
POM_DEVELOPER_ID=baishengye
POM_DEVELOPER_NAME=Baisheng Ye
POM_DEVELOPER_URL=https://github.com/baishengye
